"""initialising_fresh_tables

Revision ID: c5a1b3990228
Revises: 
Create Date: 2026-07-15 01:21:28.630156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a1b3990228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('genre_csv', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_activity_logs_id'), 'admin_activity_logs', ['id'], unique=False)
    op.create_table('circles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circles_id'), 'circles', ['id'], unique=False)
    op.create_index(op.f('ix_circles_name'), 'circles', ['name'], unique=False)
    op.create_index(op.f('ix_circles_owner_id'), 'circles', ['owner_id'], unique=False)
    op.create_index(op.f('ix_circles_slug'), 'circles', ['slug'], unique=True)
    op.create_table('library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('bookmark_page', sa.Integer(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_library_user_book')
    )
    op.create_index(op.f('ix_library_items_id'), 'library_items', ['id'], unique=False)
    op.create_index(op.f('ix_library_items_status'), 'library_items', ['status'], unique=False)
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_user_connection_pair')
    )
    op.create_index(op.f('ix_user_connections_addressee_id'), 'user_connections', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_index(op.f('ix_user_connections_requester_id'), 'user_connections', ['requester_id'], unique=False)
    op.create_index(op.f('ix_user_connections_status'), 'user_connections', ['status'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('density', sa.String(length=20), nullable=False),
    sa.Column('reading_mode', sa.String(length=20), nullable=False),
    sa.Column('font_size', sa.String(length=20), nullable=False),
    sa.Column('line_height', sa.String(length=20), nullable=False),
    sa.Column('auto_bookmark', sa.Boolean(), nullable=False),
    sa.Column('show_progress_bar', sa.Boolean(), nullable=False),
    sa.Column('email_updates', sa.Boolean(), nullable=False),
    sa.Column('reading_reminders', sa.Boolean(), nullable=False),
    sa.Column('product_announcements', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False),
    sa.Column('share_reading_activity', sa.Boolean(), nullable=False),
    sa.Column('preferred_genres', sa.JSON(), nullable=False),
    sa.Column('reading_goals', sa.JSON(), nullable=False),
    sa.Column('content_styles', sa.JSON(), nullable=False),
    sa.Column('preferred_lengths', sa.JSON(), nullable=False),
    sa.Column('weekly_target', sa.String(length=80), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('circle_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title_override', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'book_id', name='uq_circle_book_pair')
    )
    op.create_index(op.f('ix_circle_books_book_id'), 'circle_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_circle_books_circle_id'), 'circle_books', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circle_books_id'), 'circle_books', ['id'], unique=False)
    op.create_index(op.f('ix_circle_books_status'), 'circle_books', ['status'], unique=False)
    op.create_table('circle_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'user_id', name='uq_circle_member_pair')
    )
    op.create_index(op.f('ix_circle_members_circle_id'), 'circle_members', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circle_members_id'), 'circle_members', ['id'], unique=False)
    op.create_index(op.f('ix_circle_members_user_id'), 'circle_members', ['user_id'], unique=False)
    op.create_table('circle_progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('circle_book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_item_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('bookmark_page', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_book_id'], ['circle_books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_progress_updates_circle_book_id'), 'circle_progress_updates', ['circle_book_id'], unique=False)
    op.create_index(op.f('ix_circle_progress_updates_circle_id'), 'circle_progress_updates', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circle_progress_updates_created_at'), 'circle_progress_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_circle_progress_updates_id'), 'circle_progress_updates', ['id'], unique=False)
    op.create_index(op.f('ix_circle_progress_updates_user_id'), 'circle_progress_updates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circle_progress_updates_user_id'), table_name='circle_progress_updates')
    op.drop_index(op.f('ix_circle_progress_updates_id'), table_name='circle_progress_updates')
    op.drop_index(op.f('ix_circle_progress_updates_created_at'), table_name='circle_progress_updates')
    op.drop_index(op.f('ix_circle_progress_updates_circle_id'), table_name='circle_progress_updates')
    op.drop_index(op.f('ix_circle_progress_updates_circle_book_id'), table_name='circle_progress_updates')
    op.drop_table('circle_progress_updates')
    op.drop_index(op.f('ix_circle_members_user_id'), table_name='circle_members')
    op.drop_index(op.f('ix_circle_members_id'), table_name='circle_members')
    op.drop_index(op.f('ix_circle_members_circle_id'), table_name='circle_members')
    op.drop_table('circle_members')
    op.drop_index(op.f('ix_circle_books_status'), table_name='circle_books')
    op.drop_index(op.f('ix_circle_books_id'), table_name='circle_books')
    op.drop_index(op.f('ix_circle_books_circle_id'), table_name='circle_books')
    op.drop_index(op.f('ix_circle_books_book_id'), table_name='circle_books')
    op.drop_table('circle_books')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_connections_status'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_requester_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_index(op.f('ix_user_connections_addressee_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_index(op.f('ix_library_items_status'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_id'), table_name='library_items')
    op.drop_table('library_items')
    op.drop_index(op.f('ix_circles_slug'), table_name='circles')
    op.drop_index(op.f('ix_circles_owner_id'), table_name='circles')
    op.drop_index(op.f('ix_circles_name'), table_name='circles')
    op.drop_index(op.f('ix_circles_id'), table_name='circles')
    op.drop_table('circles')
    op.drop_index(op.f('ix_admin_activity_logs_id'), table_name='admin_activity_logs')
    op.drop_table('admin_activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
