from sqlalchemy import select, text , null
from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.models import Book

BOOK_SEED = [
  {
    "title": "Mere Christianity",
    "author": "C.S. Lewis",
    "cover": "/merechristianity.png",
    "description": "A classic exploration of the common ground upon which all of those of Christian faith stand together.",
    "rating": 4.8,
    "pages": 251,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Purpose Driven Life",
    "author": "Rick Warren",
    "cover": "/thepurposedrivenlife.jpg",
    "description": "A 40-day spiritual journey to help you understand why you are alive and God's amazing plan for you.",
    "rating": 4.7,
    "pages": 340,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Crazy Love",
    "author": "Francis Chan",
    "cover": "/crazylove.jpg",
    "description": "A call for Christians to fall in love with God and live out their faith in a radical way.",
    "rating": 4.7,
    "pages": 224,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Case for Christ",
    "author": "Lee Strobel",
    "cover": "/thecaseforchrist.jpg",
    "description": "A journalist's personal investigation of the evidence for Jesus Christ.",
    "rating": 4.8,
    "pages": 263,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Holy Bible (KJV)",
    "author": "Various Authors",
    "cover": "/kingjamesbibleholybiblekjvannotated.jpg",
    "description": "The King James Version of the Holy Bible.",
    "rating": 5.0,
    "pages": 742,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null

  },
  {
    "title": "Knowing God",
    "author": "J.I. Packer",
    "cover": "/knowinggod.jpg",
    "description": "A profound work that reveals the character and majesty of God.",
    "rating": 4.8,
    "pages": 535,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Pursuit of God",
    "author": "A.W. Tozer",
    "cover": "/thepursuitofgod.png",
    "description": "A thirsty cry for a deeper life with God.",
    "rating": 4.8,
    "pages": 128,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Desiring God",
    "author": "John Piper",
    "cover": "/desiringgod.jpg",
    "description": "Finding supreme joy in God through 'Christian Hedonism.'",
    "rating": 4.7,
    "pages": 399,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Gentle and Lowly",
    "author": "Dane Ortlund",
    "cover": "/gentleandlowly.jpg",
    "description": "An exploration of the heart of Christ for sinners and sufferers.",
    "rating": 4.8,
    "pages": 224,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Radical",
    "author": "David Platt",
    "cover": "/radical-David-Platt.jpg",
    "description": "Taking back your faith from the American Dream.",
    "rating": 4.7,
    "pages": 26,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Holy Bible",
    "author": "Various Authors",
    "cover": "/theholybible.jpg",
    "description": "Translated out of the Original Tongues: and with the Former Translations Diligently Comparedand Revised, by His Majesty’s Special Command.",
    "rating": 5.0,
    "pages": 2462,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Holy Bible (LSV)",
    "author": "Various Authors",
    "cover": "/theholybible-lsv.jpg",
    "description": "The Literal Standard Version of the Holy Bible.",
    "rating": 5.0,
    "pages": 771,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Prayer Fasting & the Pursuit of God",
    "author": "David Platt",
    "cover": "/prayerfastingandthepursuitofgod-david-platt.jpeg",
    "description": "A practical guide to prayer, fasting, and the pursuit of God.",
    "rating": 4.6,
    "pages": 260,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Holy Bible (NIV)",
    "author": "Various Authors",
    "cover": "/theholybible-niv.jpg",
    "description": "The New International Version of the Holy Bible.",
    "rating": 5.0,
    "pages": 1751,
    "genre": ["Christianity", "Faith"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },

  #--- PRODUCTIVITY ---
  {
    "title": "Atomic Habits",
    "author": "James Clear",
    "cover": "/atomichabits.jpg",
    "description": "Tiny changes, remarkable results through habit stacking and identity shift.",
    "rating": 4.8,
    "pages": 320,
    "genre": ["Productivity","Self-Help","Health"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Deep Work",
    "author": "Cal Newport",
    "cover": "/deepwork-calnewport.webp",
    "description": "Rules for focused success in a distracted world.",
    "rating": 4.7,
    "pages": 190,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The 7 Habits of Highly Effective People",
    "author": "Stephen Covey",
    "cover": "/the7habitsofhighlyeffectivepeople-25th-Anni-Edition.png",
    "description": "A principle-centered approach for solving personal and professional problems.",
    "rating": 4.8,
    "pages": 282,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Eat That Frog!",
    "author": "Brian Tracy",
    "cover": "/eatthatfrog-brian-tracy.jpg",
    "description": "21 great ways to stop procrastinating and get more done in less time.",
    "rating": 4.7,
    "pages": 127,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Essentialism",
    "author": "Greg McKeown",
    "cover": "/essentialism.jpg",
    "description": "The disciplined pursuit of less.",
    "rating": 4.6,
    "pages": 236,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Power of Habit",
    "author": "Charles Duhigg",
    "cover": "/thepowerofhabit-in-life-business.jpg",
    "description": "Why we do what we do in life and business.",
    "rating": 4.6,
    "pages": 422,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Getting Things Done",
    "author": "David Allen",
    "cover": "/gettingthingsdone.jpeg",
    "description": "The art of stress-free productivity.",
    "rating": 4.5,
    "pages": 402,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Indistractable",
    "author": "Nir Eyal",
    "cover": "/indistractable-how-tocontrol-your-attentio.webp",
    "description": "How to control your attention and choose your life.",
    "rating": 4.6,
    "pages": 265,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Make Time",
    "author": "Jake Knapp",
    "cover": "/maketime.jpg",
    "description": "How to focus on what matters every day.",
    "rating": 4.5,
    "pages": 277,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The 5 AM Club",
    "author": "Robin Sharma",
    "cover": "/the5amclub.jpeg",
    "description": "Own your morning. Elevate your life.",
    "rating": 4.4,
    "pages": 252,
    "genre": ["Productivity"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },

  # --- MINDSET & SELF-HELP ---
  {
    "title": "Man's Search for Meaning",
    "author": "Viktor Frankl",
    "cover": "/manssearchformeaning.jpg",
    "description": "A psychiatrist's memoir of life in Nazi death camps and its lessons for spiritual survival.",
    "rating": 4.9,
    "pages": 148,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Can't Hurt Me",
    "author": "David Goggins",
    "cover": "/canthurtme.jpg",
    "description": "Master your mind and defy the odds.",
    "rating": 4.8,
    "pages": 306,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Daring Greatly",
    "author": "Brene Brown",
    "cover": "/daringgreatly.jpg",
    "description": "How the courage to be vulnerable transforms the way we live, love, parent, and lead.",
    "rating": 4.7,
    "pages": 304,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Mountain Is You",
    "author": "Brianna Wiest",
    "cover": "/themountainisyou.jpg",
    "description": "Transforming self-sabotage into self-mastery.",
    "rating": 4.7,
    "pages": 248,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "12 Rules for Life",
    "author": "Jordan Peterson",
    "cover": "/12rulesforlife.jpg",
    "description": "An antidote to chaos based on psychological and philosophical insights.",
    "rating": 4.7,
    "pages": 263,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Obstacle Is the Way",
    "author": "Ryan Holiday",
    "cover": "/theobstacleistheway.jpg",
    "description": "The timeless art of turning trials into triumph through Stoic philosophy.",
    "rating": 4.7,
    "pages": 173
    ,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Four Agreements",
    "author": "Don Miguel Ruiz",
    "cover": "/thefouragreements.jpg",
    "description": "A practical guide to personal freedom based on ancient Toltec wisdom.",
    "rating": 4.7,
    "pages": 160,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Mindset: The New Psychology of Success",
    "author": "Carol S. Dweck",
    "cover": "/mindset.jpg",
    "description": "How we can learn to fulfill our potential based on growth vs. fixed mindset.",
    "rating": 4.6,
    "pages": 306,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "cover": "/thinkingfastandslow.webp",
    "description": "An exploration of the two systems that drive the way we think.",
    "rating": 4.6,
    "pages": 533,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "cover": "/the_subtle_art_of_not_giving_a_fuck.jpg",
    "description": "A counterintuitive approach to living a good life.",
    "rating": 4.4,
    "pages": 152,
    "genre": ["Mindset"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },

  # --- BUSINESS & LEADERSHIP ---
  {
    "title": "Shoe Dog",
    "author": "Phil Knight",
    "cover": "/shoedog.jpg",
    "description": "A memoir by the creator of Nike.",
    "rating": 4.8,
    "pages": 400,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Extreme Ownership",
    "author": "Jocko Willink",
    "cover": "/extremeownership.jpg",
    "description": "How U.S. Navy SEALs lead and win.",
    "rating": 4.8,
    "pages": 209,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Never Split the Difference",
    "author": "Chris Voss",
    "cover": "/neversplitthedifference.jpg",
    "description": "Negotiating as if your life depended on it.",
    "rating": 4.8,
    "pages": 288,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Good to Great",
    "author": "Jim Collins",
    "cover": "/goodtogreat.png",
    "description": "Why some companies make the leap and others don't.",
    "rating": 4.7,
    "pages": 320,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Start with Why",
    "author": "Simon Sinek",
    "cover": "/startwithwhy.jpg",
    "description": "How great leaders inspire everyone to take action.",
    "rating": 4.7,
    "pages": 271,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Hard Thing About Hard Things",
    "author": "Ben Horowitz",
    "cover": "/thehardthing.jpg",
    "description": "Building a business when there are no easy answers.",
    "rating": 4.7,
    "pages": 253,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Leaders Eat Last",
    "author": "Simon Sinek",
    "cover": "/leaderseatlast.jpg",
    "description": "Why some teams pull together and others don't.",
    "rating": 4.7,
    "pages": 296,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Zero to One",
    "author": "Peter Thiel",
    "cover": "/zerotoone.jpg",
    "description": "Notes on startups, or how to build the future.",
    "rating": 4.6,
    "pages": 213,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Lean Startup",
    "author": "Eric Ries",
    "cover": "/theleanstartup.jpg",
    "description": "How constant innovation creates radically successful businesses.",
    "rating": 4.6,
    "pages": 296,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Built to Last",
    "author": "Jim Collins",
    "cover": "/builttolast.jpg",
    "description": "Successful habits of visionary companies.",
    "rating": 4.6,
    "pages": 725,
    "genre": ["Business"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },

  # --- FINANCE ---
  {
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "cover": "/psychologyofmoney.jpg",
    "description": "Timeless lessons on wealth, greed, and happiness.",
    "rating": 4.7,
    "pages": 242,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "I Will Teach You to Be Rich",
    "author": "Ramit Sethi",
    "cover": "/iwillteachyou.jpg",
    "description": "A 6-week program that works on your rich life.",
    "rating": 4.7,
    "pages": 448,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Think and Grow Rich",
    "author": "Napoleon Hill",
    "cover": "/thinkandgrowrich.png",
    "description": "The landmark bestseller on personal success.",
    "rating": 4.7,
    "pages": 253,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Richest Man in Babylon",
    "author": "George S. Clason",
    "cover": "/richestmaninbabylon.avif",
    "description": "Success secrets of the ancients.",
    "rating": 4.7,
    "pages": 163,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Rich Dad Poor Dad",
    "author": "Robert Kiyosaki",
    "cover": "/richdadpoordad.jpg",
    "description": "What the rich teach their kids about money that the poor and middle class do not!",
    "rating": 4.6,
    "pages": 241,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Intelligent Investor",
    "author": "Benjamin Graham",
    "cover": "/intelligentinvestor.webp",
    "description": "The definitive book on value investing.",
    "rating": 4.6,
    "pages": 641,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Your Money or Your Life",
    "author": "Vicki Robin",
    "cover": "/yourmoneyoryourlife.jpg",
    "description": "9 steps to transforming your relationship with money and achieving financial independence.",
    "rating": 4.6,
    "pages": 349,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Millionaire Next Door",
    "author": "Thomas J. Stanley",
    "cover": "/millionairenextdoor.jpg",
    "description": "The surprising secrets of America's wealthy.",
    "rating": 4.6,
    "pages": 282,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Die With Zero",
    "author": "Bill Perkins",
    "cover": "/diewithzero.jpg",
    "description": "Getting all you can from your money and your life.",
    "rating": 4.5,
    "pages": 163,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Total Money Makeover",
    "author": "Dave Ramsey",
    "cover": "/thetotalmoneymakeover.jpg",
    "description": "A proven plan for financial fitness.",
    "rating": 4.5,
    "pages": 320,
    "genre": ["Finance"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null

  },

  # --- PSYCHOLOGY & HUMAN BEHAVIOR ---
  {
    "title": "The Body Keeps the Score",
    "author": "Bessel van der Kolk",
    "cover": "/bodykeepsthescore.jpg",
    "description": "Brain, mind, and body in the healing of trauma.",
    "rating": 4.8,
    "pages": 464,
    "genre": ["Psychology","Health"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Influence: The Psychology of Persuasion",
    "author": "Robert Cialdini",
    "cover": "/influence.jpg",
    "description": "The psychology of why people say 'yes.'",
    "rating": 4.7,
    "pages": 297,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Quiet",
    "author": "Susan Cain",
    "cover": "/quiet.jpeg",
    "description": "The power of introverts in a world that can't stop talking.",
    "rating": 4.6,
    "pages": 368,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Predictably Irrational",
    "author": "Dan Ariely",
    "cover": "/predictablyirrational.jpg",
    "description": "The hidden forces that shape our decisions.",
    "rating": 4.6,
    "pages": 304,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Grit",
    "author": "Angela Duckworth",
    "cover": "/grit.jpg",
    "description": "The power of passion and perseverance.",
    "rating": 4.6,
    "pages": 352,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Flow",
    "author": "Mihaly Csikszentmihalyi",
    "cover": "/flow.webp",
    "description": "The psychology of optimal experience.",
    "rating": 4.6,
    "pages": 314,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Emotional Intelligence",
    "author": "Daniel Goleman",
    "cover": "/emotionalintelligence.jpg",
    "description": "Why it can matter more than IQ.",
    "rating": 4.5,
    "pages": 249,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Blink",
    "author": "Malcolm Gladwell",
    "cover": "/blink.jpg",
    "description": "The power of thinking without thinking.",
    "rating": 4.5,
    "pages": 320,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "The Tipping Point",
    "author": "Malcolm Gladwell",
    "cover": "/thetipping Point.jpg",
    "description": "How little things can make a big difference.",
    "rating": 4.5,
    "pages": 287,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
  },
  {
    "title": "Everything is F*cked",
    "author": "Mark Manson",
    "cover": "/everythingisfcked.jpg",
    "description": "A book about hope in a world of despair.",
    "rating": 4.4,
    "pages": 288,
    "genre": ["Psychology"],
    "source_type": "pdf",
    "content_text": "Sample content...",
    "mime_type": "application/pdf",
    "source_url": null,
    "source_path": null
    },
  # ----------technology
    {
      "title": "The Innovators",
      "author": "Walter Isaacson",
      "cover": "/theinnovators.webp",
      "description": "How a group of hackers, geniuses, and geeks created the digital revolution.",
      "rating": 4.7,
      "pages": 560,
      "genre": ["Technology"],
      "source_type": "pdf",
      "content_text": "Sample content...",
      "mime_type": "application/pdf",
      "source_url": null,
      "source_path": null
    },
    {
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "cover": "/cleancode.jpg",
      "description": "A handbook of agile software craftsmanship.",
      "rating": 4.7,
      "pages": 462,
      "genre": ["Technology"],
      "source_type": "pdf",
      "content_text": "Sample content...",
      "mime_type": "application/pdf",
      "source_url": null,
      "source_path": null
    },
    {
        "title": "The Coming Wave",
        "author": "Mustafa Suleyman",
        "cover": "/thecomingwave.webp",
        "description": "A guide to navigating the era of AI and synthetic biology.",
        "rating": 4.4,
        "pages": 432,
        "genre": ["Technology", "Politics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Chip War",
        "author": "Chris Miller",
        "cover": "/chipwar.jpg",
        "description": "The epic battle over the world's most critical technology.",
        "rating": 4.5,
        "pages": 464,
        "genre": ["Technology", "History"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "The Age of Surveillance Capitalism",
        "author": "Shoshana Zuboff",
        "cover": "/surveillancecapitalism.jpg",
        "description": "The fight for a human future at the new frontier of power.",
        "rating": 4.3,
        "pages": 478,
        "genre": ["Technology", "Sociology"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Life 3.0",
        "author": "Max Tegmark",
        "cover": "/life30.jpg",
        "description": "Being human in the age of Artificial Intelligence.",
        "rating": 4.1,
        "pages": 440,
        "genre": ["Technology", "Science"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      # Science
      {
        "title": "Sapiens",
        "author": "Yuval Noah Harari",
        "cover": "/sapiens.jpg",
        "description": "A brief history of humankind from evolution to the future.",
        "rating": 4.4,
        "pages": 439,
        "genre": ["Science", "History"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Astrophysics for People in a Hurry",
        "author": "Neil deGrasse Tyson",
        "cover": "/astrophysics.jpg",
        "description": "Essential universe concepts explained simply.",
        "rating": 4.3,
        "pages": 124,
        "genre": ["Science", "Physics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "The Selfish Gene",
        "author": "Richard Dawkins",
        "cover": "/selfishgene.jpg",
        "description": "A classic look at the biology of selfishness and altruism.",
        "rating": 4.2,
        "pages": 384,
        "genre": ["Science", "Biology"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "The Gene: An Intimate History",
        "author": "Siddhartha Mukherjee",
        "cover": "/thegene.jpg",
        "description": "The story of the quest to decipher the master-code of humanity.",
        "rating": 4.3,
        "pages": 608,
        "genre": ["Science", "Biology"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "An Immense World",
        "author": "Ed Yong",
        "cover": "/immenseworld.jpg",
        "description": "How animal senses reveal the hidden realms around us.",
        "rating": 4.5,
        "pages": 464,
        "genre": ["Science", "Nature"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      # Health
      {
        "title": "Outlive",
        "author": "Peter Attia",
        "cover": "/outlive.jpg",
        "description": "The science and art of longevity and healthspan.",
        "rating": 4.7,
        "pages": 496,
        "genre": ["Health", "Longevity"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Glucose Revolution",
        "author": "Jessie Inchauspé",
        "cover": "/glucoserevolution.jpg",
        "description": "How balancing your blood sugar can transform your life.",
        "rating": 4.6,
        "pages": 320,
        "genre": ["Health", "Nutrition"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Breath",
        "author": "James Nestor",
        "cover": "/breath.jpg",
        "description": "The new science of a lost art and how we breathe.",
        "rating": 4.5,
        "pages": 226,
        "genre": ["Health", "Science"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Why We Sleep",
        "author": "Matthew Walker",
        "cover": "/whywesleep.jpg",
        "description": "Unlocking the power of sleep and dreams.",
        "rating": 4.6,
        "pages": 368,
        "genre": ["Health", "Science"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },

      # university catalogues
      {
        "title": "Shaping The College Curriculum: Academic Plans 2nd Edition",
        "author": "Lisa R. Lattuca and Joan S. Stark",
        "cover": "/shapingcollegecurriculum2nd.jpg",
        "description": "A sample: A collection of academic plans from the University of Chicago between 1892 and 1945, showcasing the evolution of higher education curriculum design.",
        "rating": 4.5,
        "pages": 30,
        "genre": ["Education", "History"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "University Teaching in Focus",
        "author": "Edited by Lynne Hunt and Denise Chalmers",
        "cover": "/universityteachingfocus.jpg",
        "description": "A sample: The second edition of University Teaching in Focus distils the knowledge and insights,of internationally acclaimed experts in university teaching. It empowers university teachers and contributes to their career success by developing their teaching skills, strategies and knowledge..",
        "rating": 4.3,
        "pages": 38,
        "genre": ["Education", "Pedagogy"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "General Education Essentials: A Guide for College Faculty",
        "author": "Paul Hanstedt",
        "cover": "/generaleducationessentials.jpg",
        "description": "A sample: A comprehensive guide to general education principles and practices for college faculty.",
        "rating": 4.2,
        "pages": 28,
        "genre": ["Education", "Pedagogy"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Business Accounting",
        "author": "Joe Ben Hoyle, University of Richmond,C. J. Skender, University of North Carolina at Chapel Hill",
        "cover": "/businessaccounting.webp",
        "description": "A sample: A comprehensive guide to business accounting principles and practices.",
        "rating": 4.3,
        "pages": 1108,
        "genre": ["Business", "Accounting"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Marketing Management",
        "author": "Maharshi Dayanand University",
        "cover": "/marketingmanagement.jpg",
        "description": "A sample: A comprehensive guide to marketing management principles and practices.",
        "rating": 4.4,
        "pages": 487,
        "genre": ["Business", "Marketing"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Marketcing Management 14",
        "author": "Philip Kotler, Northwestern University, Kevin Lane Keller, Dartmouth College",
        "cover": "/marketingmanagement14.jpg",
        "description": "A comprehensive guide to marketing management principles and practices.",
        "rating": 4.5,
        "pages": 812,
        "genre": ["Business", "Marketing"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Principles of Management",
        "author": "Rice University",
        "cover": "/principlesofmanagement.webp",
        "description": "A comprehensive guide to principles of management for business students.",
        "rating": 4.3,
        "pages": 673,
        "genre": ["Business", "Management"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Economics",
        "author": "Unknown",
        "cover": "/economics.jpg",
        "description": "A comprehensive guide to economics principles and practices.",
        "rating": 4.2,
        "pages": 110,
        "genre": ["Business", "Economics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Essential of Business Law 10th edition",
        "author": "Anthony L. Liuzzo, J.D., Ph.D.Wilkes University Mesa, Arizona, Ruth C. Hughes, J.D. ,Wilkes University Wilkes-Barre, Pennsylvania",
        "cover": "/essentialofbusinesslaw10thedition.jpeg",
        "description": "A comprehensive guide to business law principles and practices,.",
        "rating": 4.3,
        "pages": 824,
        "genre": ["Business", "Law"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Chemistry: The Central Science 12th edition",
        "author": "Theodore L. Brown University of Illinois at Urbana-ChampaignH. Eugene LEMay, Jr. University of Nevada, RenoBruce E. Bursten University of Tennessee, KnoxvilleCatherine J. Murphy ,University of Illinois at Urbana-Champaign,Patrick M. Woodward The Ohio State University",
        "cover": "/chemistryscience12thed.webp",
        "description": "A comprehensive guide to chemistry principles and practices.",
        "rating": 4.4,
        "pages": 1195,
        "genre": ["Science", "Chemistry"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "University Physics Volume 1",
        "author": "Samuel J. Ling, University of Oregon, Jeff Sanny, University of Oregon, William Moebs, University of Oregon",
        "cover": "/universityphysics.jpg",
        "description": "A comprehensive guide to university physics principles and practices.",
        "rating": 4.5,
        "pages": 998,
        "genre": ["Science", "Physics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Biology",
        "author": "Raven Johnson",
        "cover": "/Biology-6th-ed-raven-johnson-1-320.webp",
        "description": "A comprehensive guide to biology principles and practices.",
        "rating": 4.4,
        "pages": 1239,
        "genre": ["Science", "Biology"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Higher Engineering Mathematics 6th edition",
        "author": "John Bird, B.S. Grewal",
        "cover": "/higherengineeringmathematics.jpg",
        "description": "A comprehensive guide to higher engineering mathematics principles and practices.",
        "rating": 4.3,
        "pages": 705,
        "genre": ["Engineering", "Mathematics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "A Textbook of Electrical Technology Volume 1",
        "author": "B.L. Theraja, A.K. Theraja",
        "cover": "/electricaltechnology.png",
        "description": "A comprehensive guide to electrical technology principles and practices.",
        "rating": 4.2,
        "pages": 2744,
        "genre": ["Engineering", "Electrical"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Engineering Mechanics: Statics",
        "author": "R.C. Hibbeler",
        "cover": "/engineeringmechanicsstatic.jpg",
        "description": "A comprehensive guide to engineering mechanics principles and practices.",
        "rating": 4.3,
        "pages": 655,
        "genre": ["Engineering", "Mechanics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title":"Newnes Workshop Engineers pocket book",
        "author": "Roger Timings",
        "cover": "/newnesworkshopengineerspocketbook.jpg",
        "description": "A comprehensive guide to workshop engineering principles and practices.",
        "rating": 4.1,
        "pages": 315,
        "genre": ["Engineering", "Workshop"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Fluid Mechanics 4th edition",
        "author": "Frank M. White, University of Rhode Island",
        "cover": "/fluidmechanics.jpg",
        "description": "A comprehensive guide to fluid mechanics principles and practices.",
        "rating": 4.2,
        "pages": 1023,
        "genre": ["Engineering", "Fluid Mechanics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Doing Qualitative Research 5th edition",
        "author": "David Silverman",
        "cover": "/doingqualitativeresearch.jpg",
        "description": "A comprehensive guide to qualitative research principles and practices.",
        "rating": 4.3,
        "pages": 931,
        "genre": ["Research", "Qualitative"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Everythings an Argument with Readings:Instructors Notes 4th edition",
        "author": "Andrea Lunsford, Robert E. Scott",
        "cover": "/everythingsanargument.jpg",
        "description": "A comprehensive guide to argumentation principles and practices.",
        "rating": 4.2,
        "pages": 251,
        "genre": ["Communication", "Argumentation"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "The Penguin Dictionary OF International Relations",
        "author": "Graham Evans and Jeffrey Neumham",
        "cover": "/penguindictionaryofinternationalrelations.jpg",
        "description": "A comprehensive guide to international relations principles and practices.",
        "rating": 4.1,
        "pages": 644,
        "genre": ["Politics", "International Relations"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Socialogy 5th edition",
        "author": "Anthony Giddens, Mitchell Duneier, Richard P. Appelbaum, Deborah Carr",
        "cover": "/sociology.jpg",
        "description": "A comprehensive guide to sociology principles and practices.",
        "rating": 4.2,
        "pages": 1121,
        "genre": ["Sociology"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Operating System Concepts 8th edition",
        "author": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
        "cover": "/operatingsystemconcepts.jpg",
        "description": "A comprehensive guide to operating system concepts and practices.",
        "rating": 4.4,
        "pages": 976,
        "genre": ["Technology", "Operating Systems"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Operating System Concepts 8th edition",
        "author": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
        "cover": "/operatingsystemconcepts.jpg",
        "description": "A comprehensive guide to operating system concepts and practices.",
        "rating": 4.4,
        "pages": 976,
        "genre": ["Technology", "Operating Systems"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Data Communications & Networking 4th Edition",
        "author": "Behrouz A. Forouzan,DeAnza College, Sophia Chung Fegan",
        "cover": "/datacommunicationsandnetworking.jpg",
        "description": "A comprehensive guide to data communications and networking principles and practices.",
        "rating": 4.3,
        "pages": 1171,
        "genre": ["Technology", "Networking"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Data Communications & Networking 5th Edition",
        "author": "Behrouz A. Forouzan,DeAnza College, Sophia Chung Fegan",
        "cover": "/datacommunicationsandnetworking.jpg",
        "description": "A comprehensive guide to data communications and networking principles and practices.",
        "rating": 4.3,
        "pages": 1269,
        "genre": ["Technology", "Networking"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Java How To Program GUI 9th Edition",
        "author": "Paul Deitel, Harvey Deitel",
        "cover": "/javahowtoprogram.jpg",
        "description": "A comprehensive guide to Java programming principles and practices.",
        "rating": 4.4,
        "pages": 1535,
        "genre": ["Technology", "Programming"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Java How To Program GUI 4th Edition",
        "author": "Paul Deitel, Harvey Deitel",
        "cover": "/javahowtoprogram.jpg",
        "description": "A comprehensive guide to Java programming principles and practices.",
        "rating": 4.4,
        "pages": 1530,
        "genre": ["Technology", "Programming"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Java How To Program 10th Edition",
        "author": "Paul Deitel, Harvey Deitel",
        "cover": "/javahowtoprogram10thed.jpg",
        "description": "A comprehensive guide to Java programming principles and practices.",
        "rating": 4.4,
        "pages": 1245,
        "genre": ["Technology", "Programming"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Database System Concepts 7th Edition",
        "author": "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
        "cover": "/databasesystemconcepts.jpg",
        "description": "A comprehensive guide to database system concepts and practices.",
        "rating": 4.5,
        "pages": 1373,
        "genre": ["Technology", "Databases"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Introduction to Philosophy",
        "author": "Paul J. Glenn",
        "cover": "/introductiontophilosophy.jpg",
        "description": "A comprehensive guide to philosophy principles and practices,Paul J. Glenn ,Ph.D., S.T.D.Professor of Philosophy in the C ollege of St. Charles Borromeo,Columbus, Ohio.",
        "rating": 4.3,
        "pages": 418,
        "genre": ["Philosophy"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "A short textbook of a Psychiatry 7th edition",
        "author": "Niraj Ahuja",
        "cover": "/shorttextbookofpsychiatry7thed.jpg",
        "description": "A comprehensive guide to psychiatry principles and practices.",
        "rating": 4.2,
        "pages": 273,
        "genre": ["Medicine", "Psychiatry"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Semantics",
        "author": "John I. Saeed",
        "cover": "/semantics.jpg",
        "description": "A comprehensive guide to semantics principles and practices.",
        "rating": 4.3,
        "pages": 437,
        "genre": ["Linguistics", "Semantics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title":" Thomas Culculas 13th edition",
        "author": "George B. Thomas, Jr., Maurice D. Weir, Joel Hass",
        "cover": "/thomascalculus.jpg",
        "description": "A comprehensive guide to calculus principles and practices.",
        "rating": 4.4,
        "pages": 1205,
        "genre": ["Mathematics", "Calculus"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Linear Algebra and Its Applications 5th edition",
        "author": "David C. Lay, Steven R. Lay, Judi J. McDonald",
        "cover": "/linealgebra5thed.jpg",
        "description": "A comprehensive guide to linear algebra principles and practices.",
        "rating": 4.3,
        "pages": 579,
        "genre": ["Mathematics", "Linear Algebra"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Linear Algebra and Its Applications 4th edition",
        "author": "Gilbert Strang",
        "cover": "/linealgebra4thed.webp",
        "description": "A comprehensive guide to linear algebra principles and practices.",
        "rating": 4.3,
        "pages": 545,
        "genre": ["Mathematics", "Linear Algebra"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title":" An Introduction to Statistical Methods and Data Analysis 7th edition",
        "author": "R. Lyman Ott, Michael Longnecker",
        "cover": "/introductiontostatisticalmethods7th.webp",
        "description": "A comprehensive guide to statistical methods and data analysis.",
        "rating": 4.2,
        "pages": 1192,
        "genre": ["Mathematics", "Statistics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "An Introduction to Statistical Methods and Data Analysis 6th edition",
        "author": "R. Lyman Ott, Michael Longnecker",
        "cover": "/introductiontostatisticalmethods6th.jpg",
        "description": "A comprehensive guide to statistical methods and data analysis.",
        "rating": 4.2,
        "pages": 1297,
        "genre": ["Mathematics", "Statistics"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Elementary Differential Equations and Boundary Value Problems 7th edition",
        "author": "William E. Boyce, Richard C. DiPrima",
        "cover": "/elementarydifferentialequations7thed.jpg",
        "description": "A comprehensive guide to elementary differential equations and boundary value problems.",
        "rating": 4.3,
        "pages": 761,
        "genre": ["Mathematics", "Differential Equations"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Elementary Differential Equations and Boundary Value Problems 11th edition",
        "author": "William E. Boyce, Richard C. DiPrima",
        "cover": "/elementarydifferentialequations11thed.webp",
        "description": "A comprehensive guide to elementary differential equations and boundary value problems.",
        "rating": 4.3,
        "pages": 1120,
        "genre": ["Mathematics", "Differential Equations"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      },
      {
        "title": "Elementary Differential Equations and Boundary Value Problems 8th edition",
        "author": "William E. Boyce, Richard C. DiPrima",
        "cover": "/elementarydifferentialequations8thed.jpg",
        "description": "A comprehensive guide to elementary differential equations and boundary value problems.",
        "rating": 4.3,
        "pages": 806,
        "genre": ["Mathematics", "Differential Equations"],
        "source_type": "pdf",
        "content_text": "Sample content...",
        "mime_type": "application/pdf",
        "source_url": null,
        "source_path": null
      }
]

def find_existing_book(db: Session, item: dict) -> Book | None:
    """
    Find an existing book.

    Priority:
    1. Match by source_url if the book has a source_url.
    2. Otherwise match by title + author.
    """

    source_url = item.get("source_url")

    if source_url:
        return db.execute(
            select(Book).where(Book.source_url == source_url)
        ).scalar_one_or_none()

    return db.execute(
        select(Book).where(
            Book.title == item["title"],
            Book.author == item["author"],
        )
    ).scalar_one_or_none()


def apply_book_seed_data(book: Book, item: dict) -> None:
    """
    Apply seed data to a Book model.

    This works for both new books and existing books.
    """

    book.title = item["title"]
    book.author = item["author"]
    book.cover = item["cover"]
    book.description = item["description"]
    book.rating = item["rating"]
    book.pages = item["pages"]

    book.source_type = item.get("source_type")
    book.content_text = item.get("content_text")
    book.mime_type = item.get("mime_type")
    book.source_url = item.get("source_url")
    book.source_path = item.get("source_path")

    book.genres = item.get("genre", [])


def seed() -> None:
    """
    Seed only books.

    This does not drop tables.
    This does not recreate the database.
    This does not recreate users.
    Existing books are updated.
    New books are inserted.
    """

    created_count = 0
    updated_count = 0

    with SessionLocal() as db:
        db: Session

        for item in BOOK_SEED:
            book = find_existing_book(db, item)

            if book is None:
                book = Book()
                apply_book_seed_data(book, item)
                db.add(book)
                created_count += 1
            else:
                apply_book_seed_data(book, item)
                updated_count += 1

        db.commit()

        books_count = db.execute(
            text("SELECT COUNT(*) AS count FROM books")
        ).scalar_one()

        print("Database connection confirmed")
        print("Seed complete")
        print(f"Created books: {created_count}")
        print(f"Updated books: {updated_count}")
        print(f"Total books in database: {books_count}")


if __name__ == "__main__":
    seed()